"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from mongoengine import connect

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*dp=#=1_ammq0*b(nybx4155bm64_7)f++mr+fd04f%z017v)g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mongoengine',
    'django_mongoengine.mongo_admin',
    'rest_framework',
    'book',
    'cart',
    'order',
    'clothes',
    'mobile',
    'shoes',
    # 'payment',
    # 'shipping',
    # 'cms',
    'customer',
    'gateway',
]

# AUTH_USER_MODEL = 'customer.Customer'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerce',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'postgresql': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecommerce',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# MongoDB settings for specific apps
MONGODB_DATABASES = {
    'book': {
        'name': 'ecommerce_books',
        'host': 'localhost',
        'port': 27017,
    },
    'mobile': {
        'name': 'ecommerce_mobile',
        'host': 'localhost',
        'port': 27017,
    },
    'shoes': {
        'name': 'ecommerce_shoes',
        'host': 'localhost',
        'port': 27017,
    },
    'clothes': {
        'name': 'ecommerce_clothes',
        'port': 27017,
        'host': 'localhost',
    }
}

# Database routers
DATABASE_ROUTERS = [
    'ecommerce.routers.DatabaseRouter',
]

# App-Database Mapping
DATABASE_APPS_MAPPING = {
    # MongoDB Apps (using mongoengine)
    'book': 'book',
    'mobile': 'mobile',
    'shoes': 'shoes',
    'clothes': 'clothes',

    # PostgreSQL Apps
    'payment': 'postgresql',
    'shipping': 'postgresql',
    'order': 'postgresql',
    'cart': 'postgresql',

    # MySQL Apps (default)
    'customer': 'default',
    'cms': 'default',
    'gateway': 'default',
}

# Nếu muốn, định nghĩa kết nối default để làm fallback
connect(
    db='default_db',
    alias='default',
    host='localhost',
    port=27017,
    authentication_source='admin',
)

# Initialize MongoDB connections
for app_name, db_config in MONGODB_DATABASES.items():
    connect(
        db=db_config['name'],
        host=db_config['host'],
        port=db_config['port'],
        alias=app_name,
        authentication_source='admin',
    )

# Rest Framework settings
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
